---
#- hosts: all
#  gather_facts: False
#install python on managed nodes if missing
 gather_facts: False
- name: install python 2
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
